def throw(error_msg):
    print(error_msg)
    exit()
